FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt -y install ca-certificates --fix-missing

RUN sed -i 's|http://archive.ubuntu.com/ubuntu|https://archive.ubuntu.com/ubuntu|g' /etc/apt/sources.list \
 && sed -i 's|http://security.ubuntu.com/ubuntu|https://security.ubuntu.com/ubuntu|g' /etc/apt/sources.list

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
      ca-certificates \
      bash \
      file \
      binutils \
      libc6:armhf \
      libstdc++6:armhf \
      zlib1g:armhf \
      libgcc-s1:armhf \
      libasound2:armhf \
      libpulse0:armhf \
      libsdl2-2.0-0:armhf \
      libx11-6:armhf \
      libxext6:armhf \
      libxrandr2:armhf \
      libxi6:armhf \
      libxcursor1:armhf \
      libxinerama1:armhf \
      libgl1:armhf \
      xvfb libgl1-mesa-dri libglx-mesa0 libegl1-mesa \
      mesa-utils \
      libopenal1:armhf \
      && rm -rf /var/lib/apt/lists/* && apt-get clean

# Nox is 32bit so might need this on Apple M1:
# docker run --privileged --rm tonistiigi/binfmt --install all

# create an app user with a stable uid/gid
RUN groupadd -g 10001 app \
 && useradd  -u 10001 -g 10001 -m -s /usr/sbin/nologin app

WORKDIR /opt/nox-decomp

RUN chown -R 10001:10001 /opt/nox-decomp

#COPY --chown=10001:10001 openal.armhf /opt/nox-decomp/openal.armhf
COPY --chown=10001:10001 ffmpeg.armhf /opt/nox-decomp/ffmpeg.armhf
COPY --chown=10001:10001 noxd.armhf /opt/nox-decomp/noxd.armhf
COPY --chown=10001:10001 server.sh /opt/nox-decomp/server.sh

RUN chmod +x /opt/nox-decomp/server.sh
RUN chmod +x /opt/nox-decomp/noxd.armhf

USER 10001:10001

ENTRYPOINT ["/opt/nox-decomp/server.sh"]
